stages: 
  data_ingestion :
  cmd : python src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_01_data_ingestion.py
  deps:
     - src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_01_dataingestion.py
     - config/config.yaml
  outs :
    - artifacts/data_ingestion/Salmonella 
    - artifacts/data_ingestion/Coccidiosis
    - artifacts/data_ingestion/Healthy
    - artifacts/data_ingestion/New Castle Disease

    

  Prepare_base_model :
   cmd : python src/CHICKEN_DISEASE_CLASSIFIACATION/Pipeline/stage_02_base_model.py
   deps :
     - python src/CHICKEN_DISEASE_CLASSIFIACATION/Pipeline/stage_02_base_model.py 
     - config/config.yaml
   params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
   outs :
      - artifacts/prepare_base_model

  Training :
   cmd : python src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_03_model_trainer.py
   deps:
     - python src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_03_model_trainer.py
     - python src/CHICKEN_DISEASE_CLASSIFICATION/components/call_back.py
     - config/config.yaml
     - artifacts/data_ingestion/Salmonella 
     - artifacts/data_ingestion/Coccidiosis
     - artifacts/data_ingestion/Healthy
     - artifacts/data_ingestion/New Castle Disease
   params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATIO
  outs :
    - artifacts/training/model.h5

  Model_evaluation :
    cmd : python src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_05_model_evaluation.py

    deps :
     - python src/CHICKEN_DISEASE_CLASSIFICATION/Pipeline/stage_05_model_evaluation.py
     - python src/CHICKEN_DISEASE_CLASSIFICATION/components/call_back.py
     - config/config.yaml
     - artifacts/data_ingestion/Salmonella 
     - artifacts/data_ingestion/Coccidiosis
     - artifacts/data_ingestion/Healthy
     - artifacts/data_ingestion/New Castle Disease
     - artifacts/training/model.h5
    params:
     - IMAGE_SIZE
     - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false



