artifacts_root: artifacts

Data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: Data_notebook/Data/Train


Prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_dir: artifacts/prepare_base_model/base_model.h5
  updated_base_model_dir: artifacts/prepare_base_model/base_model_updated.h5
