artifacts_root: artifacts

Data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: Data_notebook/Data/Train
  category_1_dir: artifacts/data_ingestion/Salmonella 
  category_2_dir: artifacts/data_ingestion/Coccidiosis
  category_3_dir: artifacts/data_ingestion/Healthy
  category_4_dir: artifacts/data_ingestion/New Castle Disease



Prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_dir: artifacts/prepare_base_model/base_model.h5
  updated_base_model_dir: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
